name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: pranshu05/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ 45f9cada-ea79-4959-b51b-2592259cdf5b }}
          GH_TOKEN: ${{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 }}
